targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
        # This will only generate code for files 
        # in specified folders.
        generate_for:
          - "**/domain/model/**.dart"
          - "**/domain/provider/**.dart"
          - "**/data/repository/**.dart"
          - "**/data/service/**.dart"
          - "api/**.dart"
          - "**/api/**.dart"
          - "env/**.dart"
      freezed|freezed:
        options:
          unionKey: 'modelType'
          copyWith: true
          fromJson: true
          toJson: true
          makeCollectionsUnmodifiable: false
        # This will only generate code for files 
        # in specified folders.
        generate_for:
          - "**/domain/model/**.dart"
          - "**/domain/provider/**.dart"
          - "**/data/repository/**.dart"
          - "**/data/service/**.dart"
          - "api/**.dart"
          - "**/api/**.dart"