name: piix_mobile
description: A piix application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  barcode_widget: ^2.0.3
  camera: ^0.10.5+4
  carousel_slider: ^4.2.1
  collection: ^1.16.0
  connectivity_plus: ^3.0.3
  connectivity_plus_web: ^1.2.5
  csv: ^5.0.1
  dio: ^5.1.2
  equatable: ^2.0.5
  envied: ^0.3.0
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.16
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  #Allows to obscure and encrypt variables
  flutter_cached_pdfview: ^0.4.1
  flutter_html_all: ^3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.2
  flutter_screenutil: ^5.6.0
  #A firebase crashlytics api
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get_it: ^7.2.0
  image: ^3.1.3
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: any
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  logger: ^1.1.0
  multi_select_flutter: ^4.1.3
  path: ^1.8.2
  path_provider: ^2.0.11
  pdf: ^3.8.4
  permission_handler: ^11.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  signature: ^5.3.0
  #Provides platform specific location services
  riverpod_annotation: ^2.0.2
  super_tooltip: ^2.0.4
  url_launcher: ^6.1.7
  whatsapp_unilink: ^2.1.0
  wakelock: ^0.4.0
  

dev_dependencies:
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mockito: ^5.3.2
  #Allows to annotate classes for automatic json serialization generation
  build_runner: ^2.4.6
  custom_lint:
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # assets:
    # - assets/images/
    # - assets/images/login/
    # - assets/images/svg_image_icons/
    # - assets/images/svg_images/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
  #Controls screen awake time
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 900
    - family: PiixIcons
      fonts:
        - asset: assets/icons/PiixIcons.ttf
