name: piix_mobile
description: A piix application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  #Creates a barcode 
  barcode_widget: ^2.0.3
  #Caches the image to avoid downloading it each time it is needed to be shown
  cached_network_image: ^3.3.1
  #Allows access to camera 
  camera: ^0.10.5+4
  #Connects to firebase firestore
  cloud_firestore: ^4.15.10
  #Contains a library of utilities to handle a collection structure
  collection: ^1.16.0
  #Allows to detect wifi or cellular connection ios and android
  connectivity_plus: ^3.0.3
  #Allows to detect wifi or cellular connection in web
  connectivity_plus_web: ^1.2.5
  #A codec to transform data into a csv file
  csv: ^5.0.1
  #An HTTP Request api
  dio: ^5.1.2
  #Allows to comapre objects
  equatable: ^2.0.5
  #Allows to obscure and encrypt variables
  envied: ^0.3.0+3
  #A firebase analytics api
  firebase_analytics: ^10.8.7
  #A firebase auth api
  firebase_auth: ^4.17.6
  #A firebase central api to control the firebase instance
  firebase_core: ^2.25.5
  #A firebase crashlytics api
  firebase_crashlytics: ^3.4.16
  #A firebase storage api
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  #Allows to view and cache pdf files
  flutter_cached_pdfview: ^0.4.1
  flutter_localizations:
    sdk: flutter
  #Creates a rating bar
  flutter_rating_bar: ^4.0.1
  #State management and cache handler 
  flutter_riverpod: ^2.3.2
  #Controls screen and font size
  flutter_screenutil: ^5.6.0
  #Creates a speed dial button
  flutter_speed_dial: ^6.2.0
  #Draw SVG files using Flutter
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  #Provides getting a a geocode from address or coordinates
  geocoding: ^2.0.5
  #Provides platform specific location services
  geolocator: ^9.0.2
  #Allows to navigate the app with Flutter Navigator 2.0
  go_router: ^13.2.0
  #Manipulate images in different formats
  image: ^3.1.3
  #Allows to save images in gallery
  image_gallery_saver: ^1.7.1
  #Controls camera pictures and image gallery selection
  image_picker: ^0.8.6
  #Checks internet connection
  internet_connection_checker: ^1.0.0+1
  #Allows to control localized time, dates, and even strings
  intl: any
  #Allows to annotate classes for automatic json serialization generation
  json_annotation: ^4.8.0
  #Allows to save images in gallery
  json_serializable: ^6.5.4
  #A logger library for logs
  logger: ^1.1.0
  #Allows to create path manipulation
  path: ^1.8.2
  #Allows to read current device path to store and retrieve files
  path_provider: ^2.0.11
  #Creates pdf files
  pdf: ^3.8.4
  #Controls iOS and Android Permission
  permission_handler: ^11.0.0
  #Allows to create riverpod providers
  riverpod: ^2.5.1
  #Allows to annotate certain properties as riverpod instances
  riverpod_annotation: ^2.0.2
  #Introduces Reactive X programming
  rxdart: ^0.27.7
  #Allows to store data in local persistency
  shared_preferences: ^2.0.16
  #Allows to create a text canvas which allows drawing
  signature: ^5.3.0
  #Allows to persist data in local with an object storage in ios and android
  sembast: ^3.6.0
  #Allows to persist data in local with an object storage in web
  sembast_web: ^2.2.0
  #Allows to open other type of url links
  url_launcher: ^6.1.7
  #Allows to open WhatsApp App
  whatsapp_unilink: ^2.1.0
  #Controls screen awake time
  wakelock: ^0.4.0



  
  

  
  

dev_dependencies:
  #Used to run envied in build runner
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  #Creates special classes to handle data entities with build runner
  freezed: ^2.3.2
  #Creates a mock class to be used in testing
  mocktail: ^1.0.3
  #Runs code generator
  build_runner: ^2.4.8
  custom_lint:
  #Used to tun riverpod with build runner
  riverpod_generator: ^2.3.3
  #Executes cleaning of riverpod classes 
  riverpod_lint: ^2.1.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/svgs/app_brand/
    - assets/images/
    - assets/images/1x/
    - assets/images/2x/
    - assets/images/4x/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 900
    - family: PiixIcons
      fonts:
        - asset: assets/icons/PiixIcons.ttf
