// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WuK_4pOF4U6GXjnJGsMIo7qFRPfspSA',
    appId: '1:273828342301:web:3b5944fe1b280a3ab0f4f4',
    messagingSenderId: '273828342301',
    projectId: 'piix-dev',
    authDomain: 'piix-dev.firebaseapp.com',
    databaseURL: 'https://piix-dev-default-rtdb.firebaseio.com',
    storageBucket: 'piix-dev.appspot.com',
    measurementId: 'G-0DK0KKX8LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBodonWJLh9bNH4urbx-pnj3Sta5j8mhQ0',
    appId: '1:273828342301:android:fa19d66df5537ffdb0f4f4',
    messagingSenderId: '273828342301',
    projectId: 'piix-dev',
    databaseURL: 'https://piix-dev-default-rtdb.firebaseio.com',
    storageBucket: 'piix-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAqPretBKrz0OTsJHYjDoM8-BrjJnalXc',
    appId: '1:273828342301:ios:be9747e01ddfd069b0f4f4',
    messagingSenderId: '273828342301',
    projectId: 'piix-dev',
    databaseURL: 'https://piix-dev-default-rtdb.firebaseio.com',
    storageBucket: 'piix-dev.appspot.com',
    androidClientId: '273828342301-127k1r8gf6sgegg2a25l0gkf5orrc48j.apps.googleusercontent.com',
    iosClientId: '273828342301-6897lqvns1bc8pdfg68jl71goa8289oo.apps.googleusercontent.com',
    iosBundleId: 'com.piix.app',
  );
}
