// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRPzTnbQIRwTaRh8wSFWYyJfaFghPYtU',
    appId: '1:1047659402431:web:2878b17a7a570a07f5620a',
    messagingSenderId: '1047659402431',
    projectId: 'piix-dev-env-02282024dv',
    authDomain: 'piix-dev-env-02282024dv.firebaseapp.com',
    storageBucket: 'piix-dev-env-02282024dv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByFzruO1s_VBtJiSlS1IA6AfAmTNHdjnA',
    appId: '1:1047659402431:android:d146d119bfede77ff5620a',
    messagingSenderId: '1047659402431',
    projectId: 'piix-dev-env-02282024dv',
    storageBucket: 'piix-dev-env-02282024dv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA31yZ2Kmk1NalYYgMGqSO0nHJL-14fGI',
    appId: '1:1047659402431:ios:ecf889775ccc41b0f5620a',
    messagingSenderId: '1047659402431',
    projectId: 'piix-dev-env-02282024dv',
    storageBucket: 'piix-dev-env-02282024dv.appspot.com',
    iosBundleId: 'com.piix.app',
  );
}
