// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqY8CtoWpblAF5ixK9YqqdRSEC_UaMF4',
    appId: '1:22947427370:web:d81c830ae55e31ac637f53',
    messagingSenderId: '22947427370',
    projectId: 'piix-prod-env-02282024prd',
    authDomain: 'piix-prod-env-02282024prd.firebaseapp.com',
    storageBucket: 'piix-prod-env-02282024prd.appspot.com',
    measurementId: 'G-HSFWW1PLV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYIc7JItAdZJNJYRtJaR2i7LHC6STBNmM',
    appId: '1:22947427370:android:b27764c64a2aa9af637f53',
    messagingSenderId: '22947427370',
    projectId: 'piix-prod-env-02282024prd',
    storageBucket: 'piix-prod-env-02282024prd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwB28i7_vzE1Q6UIe74A9R582UK1dY1I',
    appId: '1:22947427370:ios:286a6a36fbfa9d4c637f53',
    messagingSenderId: '22947427370',
    projectId: 'piix-prod-env-02282024prd',
    storageBucket: 'piix-prod-env-02282024prd.appspot.com',
    iosBundleId: 'com.piix.app',
  );
}
