// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:931464424503:web:3464857e21564d5a1ce3b2',
    messagingSenderId: '931464424503',
    projectId: 'piix-stage-env-02282024stg',
    authDomain: 'piix-stage-env-02282024stg.firebaseapp.com',
    storageBucket: 'piix-stage-env-02282024stg.appspot.com',
    measurementId: 'G-WC2KGJZQX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:931464424503:android:1f328f326bf7e2d51ce3b2',
    messagingSenderId: '931464424503',
    projectId: 'piix-stage-env-02282024stg',
    storageBucket: 'piix-stage-env-02282024stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:931464424503:ios:d04cbee98c4f005f1ce3b2',
    messagingSenderId: '931464424503',
    projectId: 'piix-stage-env-02282024stg',
    storageBucket: 'piix-stage-env-02282024stg.appspot.com',
    iosBundleId: 'com.piix.app.stage',
  );
}
